### ISSUE TITLE
Null when running on a docker container

### ISSUE THREAD

**Issue by jviotti** [sindresorhus/os-homedir#3]
Running this on a docker container returns `null` given that there is no `$HOME` leading to some weird issues.

Maybe we can default to something like `__dirname`, or provide an argument to set a default value? Of course the user can check the return value himself, but I'm using this module in many places among different node modules and it's unreliable to check and provide the same default everywhere.

I understand that this is a poly-fill to `os.homedir()` and deviating from the original behaviour might not be an option.

How does such function behave in a case like the mentioned one?

**Comment by sindresorhus** [comment]
There's no good universal default. It really depends on your use-case. In many cases defaulting to the current directory would work. Other cases the temp directory. I know it's annoying, but you'll have to handle it yourself. In a perfect world there would always be a home directory, but we're dealing with computers, so pretty much the opposite of perfect and consistent...

If you're fine with falling back to temp, you can use https://github.com/sindresorhus/home-or-tmp.

**Comment by jviotti** [comment]
@sindresorhus Great, `home-or-tmp` seems exactly what I'm looking for! Thanks for the help!
